### ISSUE TITLE
Expand on the topics

### ISSUE THREAD

**Issue by ghost** [ocawley/ittsqa22#1]
While the topics are listed, you should expand on them, explain how each is going to be done, what tools will be used, etc...

**Comment by David-Lawlor** [comment]
Thank you. I hope your issue has been resolved.

Join us on facebook http://www.facebook.com/ghuFjudfUhhCjhKhObhFjhbF

**Comment by ghost** [comment]
Perfect.

All the topics updated with better explanation.

Thank You!
